sudo: required
dist: trusty
language: python
services:
  - redis-server
python:
  - "3.6"
env:
  global:
    - PORT=5000
    - INTEGRATIONTEST=false
    - UNITTEST=false
  matrix:
    - BUILDBACKEND=docker INTEGRATIONTEST=true
    - UNITTEST=true

install:
  - if [[ "x$BUILDBACKEND" != "x" ]]; then ./build-scripts/setup.sh; fi
  - pip install -r dev-requirements.txt

script:
  - if [[ "x$INTEGRATIONTEST" == "xtrue" ]]; then ./build-scripts/test.sh; fi
  - if [[ "x$UNITTEST" == "xtrue" ]]; then PYTHONPATH="./tests/mocks" python tests/runtests.py; fi
